services:
  robot-cleaner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always
    networks:
      - tibber_test
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always
    networks:
      - tibber_test

networks:
  tibber_test:
    name: tibber_test
